import type { Metadata } from "next";
import "./globals.css";
import { pelak } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={pelak.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
